name: Merge Multiple Commits

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to merge into and push'
        required: true
        type: string
      target_commit:
        description: 'Target base commit SHA'
        required: true
        type: string
      source_commits:
        description: 'Space-separated list of SHAs to merge'
        required: true
        type: string
      commit_message:
        description: 'Custom message prefix for the merges'
        required: true
        type: string

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@://github.com"

      - run: |
          git checkout -B "${{ github.event.inputs.target_branch }}" "${{ github.event.inputs.target_commit }}"
          
          for commit in ${{ github.event.inputs.source_commits }}; do
            git merge "$commit" -m "${{ github.event.inputs.commit_message }} - Merging $commit" --no-ff
          done
          
          git push origin "${{ github.event.inputs.target_branch }}"
