name: Merge Commits

on:
  workflow_dispatch:
    inputs:
      source_commit:
        description: "SHA of the commit to merge FROM"
        required: true
        type: string

      target_commit:
        description: "SHA of the commit to merge INTO"
        required: true
        type: string

      branch:
        description: "Branch to apply merge on"
        required: true
        default: "main"
        type: string

      commit_message:
        description: "Custom merge commit message"
        required: true
        type: string

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - run: |
          git reset --hard "${{ inputs.target_commit }}"

      - run: |
          git merge "${{ inputs.source_commit }}" -m "${{ inputs.commit_message }}"

      - run: |
          git push origin "${{ inputs.branch }}"
